#!/usr/bin/env python3
"""
Regenerate docker-compose.override.yml and Caddyfile from ./clients/*.env.

The client files in ./clients/ are the single source of truth. Each file is
named <client>.env and must contain at least a DOMAIN=... line (plus the app
secrets). Run this after adding or editing a client, then:

    docker compose up -d

add-client.sh / remove-client.sh call this for you, so you rarely run it by hand.
"""
import os
import sys
import glob
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CLIENTS_DIR = os.path.join(HERE, "clients")

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,30}$")


def read_env(path):
    data = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip()
    return data


def load_clients():
    clients = []
    for path in sorted(glob.glob(os.path.join(CLIENTS_DIR, "*.env"))):
        name = os.path.splitext(os.path.basename(path))[0]
        if not NAME_RE.match(name):
            raise SystemExit(f"Invalid client name '{name}' (use lowercase letters, digits, dashes).")
        env = read_env(path)
        domain = env.get("DOMAIN", "").strip()
        if not domain:
            raise SystemExit(f"clients/{name}.env is missing a DOMAIN= line.")
        # A client with its own DATABASE_URL (see harden-db-roles.sh) uses its own
        # least-privilege login; others fall back to the shared superuser and are
        # reported so they get migrated.
        clients.append({"name": name, "domain": domain,
                        "own_db_url": bool(env.get("DATABASE_URL", "").strip())})
    return clients


def read_master_token():
    """The HQ master secret from deploy/vps/.env (only the HQ app ever receives it)."""
    path = os.path.join(HERE, ".env")
    if os.path.exists(path):
        return read_env(path).get("HQ_SYNC_TOKEN", "").strip()
    return ""


def render_compose(clients):
    sys.path.insert(0, os.path.join(HERE, "..", ".."))
    from hq_tokens import derive_tenant_token
    master = read_master_token()
    lines = [
        "# GENERATED by generate.py — do not edit by hand.",
        "# Add/remove clients with add-client.sh / remove-client.sh.",
        "name: coop",
        "services:",
    ]
    for c in clients:
        n = c["name"]
        lines += [
            f"  app-{n}:",
            "    build:",
            "      context: ../..",
            "      dockerfile: deploy/vps/Dockerfile",
            "    image: coop-app:latest",
            "    restart: unless-stopped",
            "    env_file:",
            f"      - ./clients/{n}.env",
            "    environment:",
            *([] if c["own_db_url"] else [
                # LEGACY: shared superuser. Run ./harden-db-roles.sh <name> to fix.
                f"      DATABASE_URL: postgresql://postgres:${{POSTGRES_PASSWORD}}@postgres:5432/coop_{n}",
            ]),
            # HQ credentials (F-09). Only the HQ app gets the master secret. Every other
            # client gets HQ_TENANT_TOKEN = HMAC(master, name): valid for that client
            # alone, so reading it from one container cannot control the others.
            *(
                ["      HQ_SYNC_TOKEN: ${HQ_SYNC_TOKEN:-}"] if (n == "hq" or not master) else
                [f"      HQ_TENANT_TOKEN: {derive_tenant_token(master, n)}"]
            ),
            "    volumes:",
            # Persist uploaded files (member photos, payout evidence) across
            # rebuilds. One volume per client so societies stay isolated.
            f"      - uploads-{n}:/app/static/uploads",
            "    depends_on:",
            "      postgres:",
            "        condition: service_healthy",
            "",
        ]
    if clients:
        lines.append("volumes:")
        for c in clients:
            lines.append(f"  uploads-{c['name']}:")
        lines.append("")
    return "\n".join(lines) + "\n"


def landing_domain():
    """The product's marketing domain to serve the static landing page at, or ''.

    Read from ./.landing-domain (server-local, gitignored) so the tooling stays
    generic. Example file contents: cooperativems.com
    """
    path = os.path.join(HERE, ".landing-domain")
    if os.path.exists(path):
        return open(path, encoding="utf-8").read().strip()
    return ""


def landing_api_client(clients):
    """Return the client app that should receive public marketing leads."""
    path = os.path.join(HERE, ".landing-api-client")
    configured = ""
    if os.path.exists(path):
        configured = open(path, encoding="utf-8").read().strip()
    names = {c["name"] for c in clients}
    if configured and configured in names:
        return configured
    if "hq" in names:
        return "hq"
    return clients[0]["name"] if clients else ""


# Headers every site gets. Defined once as a Caddy snippet and imported by each
# site block, so a change here reaches every society at the next generate.
#
# The content-security-policy ships Report-Only on purpose: the app uses inline
# <script> blocks and onclick handlers, so an enforcing policy would need
# 'unsafe-inline' anyway, and a wrong policy breaks pages for real members.
# Report-Only makes the browser tell us what would break before anything does.
# To enforce it later, drop the "-Report-Only" from the header name.
SECURITY_HEADERS = [
    "(security_headers) {",
    "    header {",
    # Force HTTPS for a year — for this hostname only. Every society's site
    # block imports this snippet, so each subdomain sends the header for itself
    # and gets the same protection.
    #
    # Deliberately WITHOUT includeSubDomains: on the apex that would commit every
    # present and future subdomain to valid HTTPS for a year, and a browser that
    # has seen it refuses a subdomain whose certificate has not issued yet — no
    # warning to click through, and nothing the server can send to undo it. New
    # clients are added by DNS and a Caddy reload, so that window is real. Each
    # host asserting HSTS for itself gets the security without betting a year of
    # availability on every future certificate.
    '        Strict-Transport-Security "max-age=31536000"',
    # Never let a browser second-guess a file's type — a classic upload attack.
    '        X-Content-Type-Options "nosniff"',
    # Nothing may frame these pages: clickjacking protection at the edge as well
    # as in the app itself.
    '        X-Frame-Options "DENY"',
    # Do not leak a member's portal URL to whatever site they click through to.
    '        Referrer-Policy "strict-origin-when-cross-origin"',
    # The app needs none of these, so an injected script cannot ask for them.
    '        Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=()"',
    # Do not advertise the web server or its version.
    "        -Server",
    (
        '        Content-Security-Policy-Report-Only "'
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net "
        "https://cdnjs.cloudflare.com https://code.jquery.com; "
        "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net "
        "https://cdnjs.cloudflare.com https://fonts.googleapis.com; "
        "font-src 'self' data: https://fonts.gstatic.com https://cdnjs.cloudflare.com; "
        "img-src 'self' data: blob: https:; "
        "connect-src 'self'; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self'"
        '"'
    ),
    "    }",
    "}",
    "",
]


def render_caddyfile(clients):
    lines = ["# GENERATED by generate.py — do not edit by hand.", ""]
    lines += SECURITY_HEADERS
    landing = landing_domain()
    if landing:
        # Serve the static marketing landing page at the apex (+ www).
        hosts = landing if landing.startswith("www.") else f"{landing}, www.{landing}"
        api_client = landing_api_client(clients)
        lines += [
            f"{hosts} {{",
        ]
        if api_client:
            lines += [
                "    @marketing_api path /api/marketing/*",
                f"    reverse_proxy @marketing_api app-{api_client}:8000",
            ]
        lines += [
            "    import security_headers",
            "    root * /srv/landing",
            "    encode gzip",
            # Clean URLs: /app and /privacy resolve to app.html and privacy.html.
            # These links go to members in text messages, where a ".html" is one
            # more thing to mistype.
            "    try_files {path} {path}.html {path}/index.html",
            "    file_server",
            "}",
            "",
        ]
    if not clients and not landing:
        # Caddy needs at least one site block to start cleanly.
        lines += [":80 {", "    respond \"No clients configured yet.\" 200", "}", ""]
    for c in clients:
        lines += [
            f"{c['domain']} {{",
            "    import security_headers",
            f"    reverse_proxy app-{c['name']}:8000",
            "}",
            "",
        ]
    return "\n".join(lines) + "\n"


def main():
    clients = load_clients()
    with open(os.path.join(HERE, "docker-compose.override.yml"), "w", encoding="utf-8") as f:
        f.write(render_compose(clients))
    with open(os.path.join(HERE, "Caddyfile"), "w", encoding="utf-8") as f:
        f.write(render_caddyfile(clients))
    if clients:
        print("Configured clients:")
        for c in clients:
            flag = "" if c["own_db_url"] else (
                "   !! still on the shared postgres SUPERUSER - run ./harden-db-roles.sh " + c["name"])
            print(f"  - {c['name']:<15} https://{c['domain']}{flag}")
    else:
        print("No clients yet. Add one with: ./add-client.sh <name> <domain>")


if __name__ == "__main__":
    main()
